### ISSUE TITLE
Cursor position in consumers#Show

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#410]
Possible prior art — Neon reverts?

**Comment by RTLS** [comment]
Every consumer is a record consumer, so every consumer has an underlying Sequence. For a consumer, the user wants to know the state of *processed*, *processing* and *to be processed* records.

* *Min active cursor*: the  value of the record\[sort_key\] that corresponds to the **min** value of id in the consumer records table
* *Max active cursor*: the value of the record\[sort_key\] that corresponds to the **max** value of id in the consumer records table for delivered records
* *Min healthy cursor*: similar to min cursor but for consumer records that are not failing
* *Min/max possible cursors*: the min and max values of the sort_key column from the underlying sequences table

**Processed**

Because consumers don’t necessarily start at the beginning of the table, we can’t say that a consumer has processed all rows below the min active cursor.

* Count: The count of rows in the sequence <= min active cursor
* Range: \[min possible cursor, min active cursor\]

**Processing**

* Count: The count of delivered records
* Range: \[min active cursor, max active cursor\]

**To process**

* Count: The fast count of values in the underlying source table with sort key >= max active cursor
* Range: \[max active cursor, max possible cursor\]

Is there something to be said about message groups?

**Comment by RTLS** [comment]
#443
